import React from 'react';
import { OfferStackItem } from '../../types';
import MarkdownRenderer from '../common/MarkdownRenderer';

// --- Reusable PDF Components for a clean, professional, print-friendly style ---
const Title: React.FC<{ children: React.ReactNode }> = ({ children }) => <h1 className="text-3xl font-bold text-gray-800 tracking-tight">{children}</h1>;
const Subtitle: React.FC<{ children: React.ReactNode }> = ({ children }) => <p className="text-md text-gray-500 mt-1">{children}</p>;

const AssetPdf: React.FC<{ asset: NonNullable<OfferStackItem['asset']> }> = ({ asset }) => {
    return (
        <div className="p-12 bg-white font-sans text-gray-900" style={{ width: '800px' }}>
            <header className="mb-8 pb-4 border-b border-gray-300">
                <p className="text-gray-500 font-semibold uppercase tracking-widest text-xs capitalize">{asset.type} Asset</p>
                <Title>{asset.name}</Title>
                <Subtitle>A high-value resource to help your customers succeed.</Subtitle>
            </header>
            <main>
                <div className="p-6 border border-gray-200 rounded-lg bg-gray-50/50">
                    <MarkdownRenderer content={asset.content} theme="light" />
                </div>
            </main>
            <footer className="mt-12 pt-6 border-t border-gray-200 text-xs text-gray-500 text-center">
                <p>Generated by Hormozi AI for your business.</p>
            </footer>
        </div>
    );
};

export default AssetPdf;
