import React from 'react';
import { GeneratedOffer, OfferStackItem } from '../../types';
import MarkdownRenderer from '../common/MarkdownRenderer';

// --- Reusable PDF Components for a clean, professional, print-friendly style ---
const Title: React.FC<{ children: React.ReactNode }> = ({ children }) => <h1 className="text-5xl font-black text-gray-900 tracking-tight">{children}</h1>;
const Subtitle: React.FC<{ children: React.ReactNode }> = ({ children }) => <p className="text-xl text-gray-600 mt-2">{children}</p>;

const AssetSection: React.FC<{ asset: NonNullable<OfferStackItem['asset']> }> = ({ asset }) => (
    <div className="break-before-page pt-12">
        <header className="mb-8 pb-4 border-b border-gray-300">
            <p className="text-gray-500 font-semibold uppercase tracking-widest text-xs capitalize">Asset // {asset.type}</p>
            <h1 className="text-3xl font-bold text-gray-800 mt-1">{asset.name}</h1>
        </header>
        <main>
            <div className="p-6 border border-gray-200 rounded-lg bg-gray-50/50">
                <MarkdownRenderer content={asset.content} theme="light" />
            </div>
        </main>
    </div>
);

const ValueStackAssetsPdf: React.FC<{ offer: GeneratedOffer }> = ({ offer }) => {
    return (
        <div className="p-12 bg-white font-sans text-gray-800" style={{ width: '800px' }}>
            <header className="text-center mb-12 pb-6 border-b-4 border-gray-300">
                <p className="text-gray-500 font-bold uppercase tracking-widest text-sm">Complete Asset Library for</p>
                <Title>"{offer.name}"</Title>
                <Subtitle>All the templates, guides, and scripts you need to deliver on your promise.</Subtitle>
            </header>
            <main>
                {offer.stack.map((item, index) => {
                    if (item.asset) {
                        return <AssetSection key={index} asset={item.asset} />;
                    }
                    return null;
                })}
            </main>
            <footer className="mt-12 pt-6 border-t border-gray-200 text-xs text-gray-500 text-center break-before-page">
                <p>Generated by Hormozi AI for your business.</p>
            </footer>
        </div>
    );
};

export default ValueStackAssetsPdf;
